export const POSTS_FETCH_REQUEST = "POSTS_FETCH_REQUEST";
export const POSTS_FETCH_SUCCESS = "POSTS_FETCH_SUCCESS";
export const POSTS_FETCH_FAIL = "POSTS_FETCH_FAIL";

export const POSTS_ADD_REQUEST = "POSTS_ADD_REQUEST";
export const POSTS_ADD_SUCCESS = "POSTS_ADD_SUCCESS";
export const POSTS_ADD_FAIL = "POSTS_ADD_FAIL";

export const POSTS_EDIT_REQUEST = "POSTS_EDIT_REQUEST";
export const POSTS_EDIT_SUCCESS = "POSTS_EDIT_SUCCESS";
export const POSTS_EDIT_FAIL = "POSTS_EDIT_FAIL";
